<h2 align = 'center'> Numpy and Pandas Understanding </h2>
<hr>
<p>This is a basic understanding numpy and pandas using jupyter notebook </p>

In [2]:
#This is a cell

print("Hello World !!!")

list_of_numbers = [1, 2, 3, 4, 5]





Hello World !!!


In [2]:
#try to calculate the sum by looping over list
sum_of_list = 0
for num in list_of_numbers:
    sum_of_list += num

print(sum_of_list)

15


In [3]:
#try to ca;culate the sum by using predefined function sum

print(sum(list_of_numbers))

15


<h3 align = 'left'> Understanging Numpy </h3>
<p> Installing Numpy from Jupyter Notebook </p>

In [5]:
#To provide cmd commands type '!' or '%' before the commands
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

array_of_numbers = np.array([1,2,3,4,5])
print([1,2,3,4,5], type([1,2,3,4,5]))
print(array_of_numbers, type(array_of_numbers))

#Mathematical equations on array

print(f"The sum of list or array using numpy : {array_of_numbers.sum()}")    
print(f"The mean of list or array using numpy :{array_of_numbers.mean()}")
print(array_of_numbers.std())
print(array_of_numbers.max())
print(array_of_numbers.min())

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>
The sum of list or array using numpy : 15
The mean of list or array using numpy :3.0
1.4142135623730951
5
1


In [3]:
#calculate sum of list of number, mean , standard deviation , maximum and minimum
print(sum(list_of_numbers)) #sum 
print((sum(list_of_numbers))/ len(list_of_numbers)) # mean

print(max(list_of_numbers))
print(min(list_of_numbers))

15
3.0
5
1


<h2 align ='center'>Understanding Dimension of Array and Matrices </h2>

In [ ]:
#Single Dimension Array
#[1,2,3]


In [2]:
matrix_A = np.array(([1,2] , [3,4]))
matrix_B = np.array(([4,5], [6,7]))

print(matrix_A + matrix_B)
print("**" *30)
print(matrix_A - matrix_B)
print("**"*30)
print(matrix_A * matrix_B)

[[ 5  7]
 [ 9 11]]
************************************************************
[[-3 -3]
 [-3 -3]]
************************************************************
[[ 4 10]
 [18 28]]


In [11]:
#Task 3
'''
WAP that asks the dimension for the matrix, Take input for each position of the matrix
Then creates matrix using list which was appending all the inputs
Finally display the matri
'''


number_of_row = int(input("Enter number of row :"))
number_of_column = int(input("Enter number of column :"))
array_in_list= []
for i in range(number_of_row):
    row_list = []
    for j in range (number_of_column):
        element = int(input(f"Enter value for position {i+1}{j+1}:"))
        row_list.append(element)
    array_in_list.append(row_list)

print(array_in_list)
matrix = np.array(array_in_list)
print(matrix)


ValueError: invalid literal for int() with base 10: ''

In [3]:
#Determinant 

determinant_A = np.linalg.det(matrix_A)
print(determinant_A)

determinant_B = np.linalg.det(matrix_B)
print(determinant_B)



-2.0000000000000004
-2.000000000000003


In [8]:
'Linear equation as : Ax = B, Solve for x , x =inv(A) * B'
solution = np.linalg.solve(matrix_A, matrix_B)
print(solution)

matrix_A = np.array(([1,2] , [3,4]))
matrix_B = np.array(([4,5], [6,7]))
c = np.array(([1,4], [3,3]))

'Linear equation as :Ax +c =B where c = scalar 10, and c = vector[[1,4], [3,3]], A = Matrix_A, B = Matrix_B'
solution2 = np.linalg.solve(matrix_A, matrix_B - c)
print(solution2)


[[-2. -3.]
 [ 3.  4.]]
[[-3.   2. ]
 [ 3.  -0.5]]


In [10]:
print(np.sqrt(16)) # calculate square root
print(np.exp(4)) # calculate exponential
print(np.sin([10, 20, 30])) # calculate sin angle
print(np.tan([10,20,30]))   # calculate tan angle

4.0
54.598150033144236
[-0.54402111  0.91294525 -0.98803162]
[ 0.64836083  2.23716094 -6.4053312 ]
