<h3>Efficient Net Learning and Understanding</h3>

<h4>Installing Required Packages</h4>

In [33]:
%pip install tensorflow

  Using cached tensorflow-2.17.0-cp312-cp312-win_amd64.whl.metadata (3.2 kB)
Using cached tensorflow-2.17.0-cp312-cp312-win_amd64.whl (2.0 kB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


<h4>Importing Dependencies</h4>

In [35]:
import tensorflow as tf
from keras.applications.efficientnet import EfficientNetB0
from PIL import Image
from sklearn.model_selection import train_test_split
import os 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


<h4>Understanding Architecture of Efficient Net</h4>

In [36]:
model = EfficientNetB0()
# model.summary() #This code is used to study data a little bit more

del model #Delete the model

<h4>Pre-Processing Datasets</h4>

In [41]:
def convert_image_to_tensor(path):
    img = Image.open(path)
    img = img.resize(224, 224) #this is done to make the model learn faster
    img = np.asarray(img)
    return img

image_list = []
labels_list = []
labels_map = {}
label_var = 0
i = "../data/natural_images"
for folder in os.listdir(i):
    labels_map[label_var]= folder
    for file in os.listdir(i + '/' + folder):
        image_list.append(i + '/' + folder + '/' + file)
        labels_list.append(label_var)
    label_var+=1

display(labels_map)

{0: 'airplane',
 1: 'car',
 2: 'cat',
 3: 'dog',
 4: 'flower',
 5: 'fruit',
 6: 'motorbike',
 7: 'person'}

In [42]:
print(len(image_list), len(labels_list))
layers = tf.keras.layers.CategoryEncoding(num_tokens=len(list(set(labels_list))), output_mode= 'one_hot')
labels_list= np.array(layers(labels_list))
print(labels_list)
image_list = np.array([convert_image_to_tensor(i)] for i in image_list)
print(image_list)

6899 6899
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
<generator object <genexpr> at 0x0000028FE299C790>


In [44]:
if np.isscalar(image_list):
    image_list = np.array([image_list])
if np.isscalar(labels_list):
    labels_list = np.array([labels_list])

x_train, x_test, y_train, y_test = train_test_split(list(image_list), list(labels_list))

TypeError: Singleton array array(<generator object <genexpr> at 0x0000028FE299C790>, dtype=object) cannot be considered a valid collection.

In [27]:
input_val = tf.keras.layers.Input(shape=(224, 224, 3))

model = EfficientNetB0(include_top=False, input_tensor=input_val, weights='imagenet')

for i in range(int(len(model.layers) * 0.75)):
    model.layers[i].trainable = False

x = tf.keras.layers.GlobalAveragePooling2D(name = "avg_pool")(model.output)
x = tf.keras.layers.BatchNormalization()(x)

top_drapout_rate= 0.2
x=tf.keras.layers.Dropout(top_drapout_rate, name='top_dropout')(x)

output = tf.keras.layers.Dense(len(labels_map), activation='softmax', name="pred")(x)

model = tf.keras.Model(inputs = input_val, outputs = output)

model.compile( optimizer="adam", loss="categorical_crossentropy", metrics=['accuracy'])

# model.summary()

<h4>Having error while doing this computer vision so watch this </h4>
<p>https://github.com/Siddhant128-bit/EfficientNet_Understanding_and_Transfer_Learning.git</p>